simp/rubygem-simp-cli

- lib/simp/cli/config/utils.rb
Before this patch, Ruby 2.0.0+ would fail the spec test for
Simp::Cli::Config::Utils.validate_openldap_hash with an encoding error
when adding string.to_s [ASCII-8BIT] and salt.to_s [UTF-8].
SIMP-38 #comment Fixed 2.0.0 encoding in Utils.validate_openldap_hash
SIMP-65 #close
> (SIMP-65) Fix ruby 2.0.0 string encoding errors

- .travis.yml
- spec/lib/simp/cli/config/item/yum_repositories_spec.rb
This commit enables non-SimpOS testing environments such as TravisCI to
skip YumRepositories tests that rely on SimpOS-specific OS components.
SIMP-112 #comment Introduced env var SIMP_SKIP_NON_SIMPOS_TESTS
SIMP-112 #close
> (SIMP-113) Skip SimpOS tests for YumRepositories

- build/rubygem-simp-cli.el6.spec
- build/rubygem-simp-cli.el7.spec
- lib/simp/cli.rb
- lib/simp/cli/config/utils.rb
Before this patch, "simp config" would fail in EL7/Ruby 1.9+, due to a
difference in the encoding of salt (ASCII-8BIT, due to a workaround for
Ruby 1.8.7) and other Strings when concatenated inside Base64.encode64.
This patch forces the encoding for salt to UTF-8 if the version of Ruby
is newer than 1.8, and bumps the gem and RPM release to 1.0.2.
SIMP-287 #close #comment Force encoding of salt to UTF-8 in ruby 2.0.0
> (SIMP-287) Fix UTF-8/ASCII-8BIT encoding error

- Gemfile
- lib/simp/cli/config/item.rb
- lib/simp/cli/config/item/log_servers.rb
- lib/simp/cli/config/item/ntp_servers.rb
- lib/simp/cli/config/item/rsync_server.rb
- lib/simp/cli/config/item/yum_repositories.rb
- spec/lib/simp/cli/config/item/log_servers_spec.rb
- spec/lib/simp/cli/config/item/ntp_servers_spec.rb
SIMP-295 #close #comment Fixed speling.
SIMP-296 #comment ntpd::servers are now optional in 'simp config'
SIMP-296 #comment log_servers are now optional in 'simp config'
SIMP-296 #close
SIMP-297 #close #comment Generated passwords pause until 'enter'.
> (SIMP-292) Fix usability issues in 'simp config'

- lib/simp/cli/config/item/yum_repositories.rb
Typo prevented packages from being symlinked to Updates.
SIMP-359 #close Updates has no packages!
> (SIMP-359) Updates repo not being populated with packages.

- .rspec
- lib/simp/cli.rb
- lib/simp/cli/commands/bootstrap.rb
- lib/simp/cli/config/item/add_ldap_to_hiera.rb
- lib/simp/cli/config/item/remove_ldap_from_hiera.rb
- lib/simp/cli/config/item_list_factory.rb
- spec/lib/simp/cli/config/item/add_ldap_to_hiera_spec.rb
- spec/lib/simp/cli/config/item/files/puppet.your.domain.yaml
- spec/lib/simp/cli/config/item/remove_ldap_from_hiera_spec.rb
- spec/lib/simp/cli/config/item/spec_helper.rb
Added an remove_ldap.rb to simp-cli to remove instances of ldap in
hieradata/hosts/#{fqdn}.yaml. Configured the item to run after the
item use_ldap returns false.
SIMP-17 #close
> (SIMP-17) Fix ldap when use_ldap is false

- build/rubygem-simp-cli.el6.spec
- build/rubygem-simp-cli.el7.spec
- lib/simp/cli.rb
- lib/simp/cli/config/item/use_fips.rb
- lib/simp/cli/config/item_list_factory.rb
- spec/lib/simp/cli/config/item/use_fips_spec.rb
Before this update, 'simp config' did not include an item to enable FIPS.  Now it does.
> (SIMP-353) Add use_fips item to 'simp config'

- lib/simp/cli/config/item/failover_log_servers.rb
- lib/simp/cli/config/item_list_factory.rb
- spec/lib/simp/cli/config/item/failover_log_servers_spec.rb
This commit updates `simp config` to ask for a list of syslog servers to
be used as failover targets.  The answer will populate the top-level
Hiera key, `failover_log_servers`.
SIMP-445 #close #comment Added failover_log_servers to `simp config`
SIMP-192 #comment Added failover_log_servers to `simp config`
> (SIMP-445) Add failover_log_servers to simp config

- lib/simp/cli/config/questionnaire.rb
Before this commit, `simp config` would fail when run on a system that
booted into FIPS mode, due to an MD5 call within yaml/store.  yaml/store
is no longer required by `simp config`, so it has been removed.
SIMP-495 #close #comment Removed `require 'yaml/store'` for FIPS mode
> (SIMP-495) Remove vestigial yaml/store require

- .gitignore
- build/rubygem-simp-cli.el6.spec
- build/rubygem-simp-cli.el7.spec
- lib/simp/cli.rb
- lib/simp/cli/commands/config.rb
- lib/simp/cli/config/item.rb
- lib/simp/cli/config/item/puppet_server.rb
- lib/simp/cli/config/item/use_fips.rb
- lib/simp/cli/config/item_list_factory.rb
In FIPS mode, the system must have the digest algorithm set to sha256
when running 'simp config'.
SIMP-499 #close #comment FIPS mode sets puppet digest_algorithm
Change-Id: If7d27c5e0d0044835b328fae22eb103d9a4d8381
> (SIMP-499) Set digest algo for 'simp config'+FIPS

- lib/simp/cli/commands/config.rb
Before this commit, 'simp config' always detected (and suggested)
`use_fips=no` even if FIPS was enabled.  This patch ensures that even
before puppet is run, `simp config` will have access to the
`fips_enabled` fact by adding `common/lib/facter` to the Facter search
path.
NOTE: This fix is naive and direct.  It is intended to address only the
(common) scenario where `simp config` is run on a freshly-installed SIMP
OS.  It will not work if the ISO changes structure or on a non-SIMP OS.
SIMP-497 #close #comment Added direct path to common/lib/facter
> (SIMP-497) Ensure path to fips_enabled fact

- build/rubygem-simp-cli.el6.spec
- build/rubygem-simp-cli.el7.spec
- lib/simp/cli.rb
- lib/simp/cli/config/item/grub_password.rb
Grub passwords were being amended in RHEL/CentOS 7.  They are now
properly replaced.
SIMP-544 #close Fix grub passwords
> (SIMP-544) Grub passwords properly replaced during config

- lib/simp/cli/commands/config.rb
- lib/simp/cli/config/item.rb
- lib/simp/cli/config/item/use_fips.rb
- lib/simp/cli/config/questionnaire.rb
Before this commit, `simp config -a ANSWERFILE` would interactively
prompt for any item that did not have an answer in the the ANSWERFILE.
The `--help` documentation hinted that the flag `-ff` would accomplish
this.
This patch adjusts several things:
- `simp config -a ANSWERFILE` fails when an item has no answer
- `simp config -A ANSWERFILE` prompts when an an item has no answer
- The misleading `--help` documentation for `-ff` has been removed
- The Config::Item `use_fips` now echoes its command unless `@silent`
SIMP-552 #close #comment `simp config -a` fails when Item has no answer
SIMP-552 #close #comment `simp config -A` asks when Item has no answer
SIMP-528 #close #comment removed confusing `-ff` note from `--help`
> (SIMP-552) Fail when answerfile does not have item

- lib/simp/cli/config/item/puppet_autosign.rb
- spec/lib/simp/cli/config/item/files/autosign.conf.new
- spec/lib/simp/cli/config/item/files/autosign.conf.used
- spec/lib/simp/cli/config/item/puppet_autosign_spec.rb
Before this patch, `simp config` needlessly queried the user for
the values of `puppet::autosign`.  This commit makes the process
non-interactive, persisiting existing content if there is any, and
adding the puppet server's FQDN when `/etc/puppet/autosign.conf` is
empty or new.
SIMP-551 #close #comment Made `puppet::autosign` non-interactive
> (SIMP-551) Make `puppet::autosign` non-interactive

- build/rubygem-simp-cli.el6.spec
- build/rubygem-simp-cli.el7.spec
- lib/simp/cli.rb
- lib/simp/cli/commands/doc.rb
Before this commit, running `simp doc` would die with errors because it
was looking in a nonexistent path.
This commit corrects the path-finding logic, re-enabling `simp doc`.
SIMP-573 #close #comment Fixed broken path logic in `simp doc`
> (SIMP-573) Fix broken path logic in `simp doc`

- lib/simp/cli/commands/bootstrap.rb
Pushed output of getent group to /dev/null.
SIMP-606 #close Print admin
> (SIMP-606) 'simp bootstrap' prints the admin group on apply.

- lib/simp/cli.rb
- lib/simp/cli/config/item/common_runlevel_default.rb
- lib/simp/cli/config/item/network_conf.rb
This update replaces `common::` references with `simplib::`
SIMP-624 #close
> (SIMP-624) Update `simp config` to use simplib

- lib/simp/cli.rb
- lib/simp/cli/commands/bootstrap.rb
Updated 'simp bootstrap' to ensure that we don't drop a bad symlink at
/etc/puppet/environments/simp/simp
SIMP-661 #close
> (SIMP-661) Fix for the bad simp symlink

- build/rubygem-simp-cli.el6.spec
- build/rubygem-simp-cli.el7.spec
- lib/simp/cli.rb
- simp-cli.gemspec
Guard requires listen as a runtime dependency so we needed to nail it
down to something that was Ruby < 2.2 safe.
SIMP-1178 #comment Vestige in this gem
> (SIMP-1178) Nail down 'listen' to Ruby < 2.2 safe

- lib/simp/cli.rb
- lib/simp/cli/commands/passgen.rb
This update fixes the `simp passgen` command to work with the default
SIMP environment location.
It now attempts to detect the environment when called using 'puppet
config print environmentpath'
SIMP-1199 #close
> (SIMP-1199) Fix `simp passgen`

- lib/simp/cli/commands/bootstrap.rb
Numerous bash redirects of STDOUT and STDERR in bootstrap.rb do not
work as intended.
> (SIMP-1523) Bash redirect does not squash STDERR

- bin/simp
- build/rubygem-simp-cli.spec
- lib/simp/cli/version.rb
Fixed logic that broke spec tests.
Upped the patch version by 2 to fix the inconsistent versioning
in the RPM header and changelog sections of the spec file.
SIMP-1725 #close
> (SIMP-1725) spec tests fail due to SIMP6 updates

- .gitignore
- Rakefile
The :rpm task needed to have :gem prepended to the list of task
prerequisites instead of the usual append.
SIMP-1864 #close
Change-Id: Iee18f6284fc48744385e4fd810b76b153790944e
> (SIMP-1864) Fix for the Rakefile

- build/rubygem-simp-cli.spec
- lib/simp/cli/commands/bootstrap.rb
- lib/simp/cli/version.rb
Before this patch, `simp bootstrap` would print deprecation warnings
about the deprecated setting `pluginsync` when run with Puppet 4.x.
This commit fixes the issue by removing the hard-coded `--pluginsync`
arguments from bootstrap's `puppet agent` command strings.
SIMP-2255 #close
> (SIMP-2255) Remove `--pluginsync` from bootstrap

- build/rubygem-simp-cli.spec
This patch bumps the global macro `cli_version` in the RPM spec file, so
RPM builds look for the correct gem.
SIMP-2255 #comment Corrected cli_version in `.spec` file
> (SIMP-2255) Correct cli_version in `.spec` file

- lib/simp/cli/config/items/action/configure_network_action.rb
- lib/simp/cli/config/items/action/set_hostname_action.rb
- lib/simp/cli/config/items/data/cli_network_dhcp.rb
- spec/lib/simp/cli/config/items/data/cli_network_dhcp_spec.rb
Only restart the network after the hostname is set, when
the network is configured via DHCP.
SIMP-2795 #close
> (SIMP-2795) Bad network restart for static config

- build/rubygem-simp-cli.spec
- lib/simp/cli/commands/bootstrap.rb
- Tweak post-bootstrap text to remove instructions to run
puppet and to make it more clear that the user must reboot
to complete the bootstrap process.
- Do not tell user existing certificates have been preserved,
when none exist.
SIMP-2990 #close
> (SIMP-2990) Fix simp bootstrap instructions

- build/rubygem-simp-cli.spec
- lib/simp/cli/config/errors.rb
- lib/simp/cli/config/items/action/check_server_yum_config_action.rb
- lib/simp/cli/config/items/action/update_os_yum_repositories_action.rb
- lib/simp/cli/config/items/item.rb
- lib/simp/cli/version.rb
- spec/lib/simp/cli/config/items/action/check_server_yum_config_action_spec.rb
- spec/lib/simp/cli/config/items/item_spec.rb
- simp config update:
- We noticed inconsistent behavior when spawning commands with
pipes, particularly a pipe to xargs.  Item execute has been
re-tooled to reject pipes, and provide users with a way to
chain commands while mitigating code flux due to change in API.
- Added the run_command method to Cli::Config::Item
- Action items updated:
- update_os_yum_repositories_action
- check_server_yum_config_action
SIMP-3210 #close
> (SIMP-3210) Remove pipes from spawned processes

- Rakefile
- build/rubygem-simp-cli.spec
This fixes an intermittent error where missing rubygems would cause the
RPM build to fail.
SIMP-3851 #close
> (SIMP-3851) Fix missing rubygem error

- .travis.yml
- Gemfile
- Rakefile
- build/rubygem-simp-cli.spec
- lib/simp/cli/config/items/action/set_grub_password_action.rb
- lib/simp/cli/config/items/data/grub_password.rb
- lib/simp/cli/config/items/data/svckill_mode.rb
- lib/simp/cli/config/items/list_item.rb
- lib/simp/cli/version.rb
- spec/bin/simp_spec.rb
- spec/lib/simp/cli/config/items/data/grub_password_spec.rb
- Reworked description and info messages to be more clear.
- Simplified instructions for entering arrays.
- Attempt (again) to work around warnings about duplicate constants
that arise because of multiple rubies in the Ruby load path
on Puppet-managed development systems.  These warning messages
break 'simp config' tests that are verifying the content of stderr.
- Add pkg:compare_latest_tag check to .travis.yml
- Extend pkg:compare_latest_tag to also check that the simp cli Ruby
version matches the version in the RPM spec file.
- Use more readily-available TravisCI containers
SIMP-4376 #close 
SIMP-3852 #comment Code changes
> (SIMP-4376) SIMP configuration of svckill::mode confusing

- build/rubygem-simp-cli.spec
- lib/simp/cli/config/items/action/set_grub_password_action.rb
- spec/lib/simp/cli/commands/config_spec.rb
- spec/lib/simp/cli/config/items/action/configure_network_action_spec.rb
- spec/lib/simp/cli/config/items/action/set_grub_password_action_spec.rb
- spec/lib/simp/cli/config/items/action/set_hostname_action_spec.rb
- Fixed code that sets GRUB password for CentOS6
- Tweaked test skip logic for gitlab. 
SIMP-4386 #close
> (SIMP-4386) simp config fails to set GRUB password CentOS6 EFI

- build/rubygem-simp-cli.spec
- lib/simp/cli/config/items/action/set_grub_password_action.rb
- spec/lib/simp/cli/config/items/action/set_grub_password_action_spec.rb
- modify the set of the grub2 password to use augeasproviders
to set password in /etc/grub.d.  This will mean you don't need
to figureout where the grub.cfg file is.
SIMP-4576 #close
SIMP-4832 #close
SIMP-4833 #close
> (SIMP-4576)  Update set grub password 

- ext/gems/highline/highline.gemspec
Comment out deprecated gemspec feature that spews warnings to stderr,
which in turn, causes simp-cli spec tests to fail.
> (SIMP-MAINT) Fix spec tests in TravisCI

- lib/simp/cli/utils.rb
- spec/lib/simp/cli/utils_spec.rb
Add logic to allow 'simp config' to determine the 'simp'
environment data directory before it exists in a non-ISO
SIMP RPM install.
This small code change requires a big explanation.
For a SIMP non-ISO RPM install, the 'simp' environment
skeleton and SIMP modules are only installed in
/usr/share/simp.  They are not automatically copied over
to the the puppet environments directory.  'simp config'
detects the missing 'simp' environment, and, using the
simp-adapter, executes that copy.
Unfortunately, as currently written, 'simp config' needs
to know the 'simp' environment data directory *before* it
executes the environment copy.  This is because 'simp config'
uses the 'simp' environment data directory to configure other
'simp config' actions at the time it generates its internal
decision …
> (SIMP-5476) 'simp config' fails for non-ISO RPM install

- .travis.yml
- build/rubygem-simp-cli.spec
- lib/simp/cli/commands/bootstrap.rb
- lib/simp/cli/version.rb
- spec/lib/simp/cli/commands/bootstrap_spec.rb
- Added a `simp bootstrap` option to set the wait time for
the puppetserver to start during the bootstrap process.
- Adjusted the help message so it will fit within an
80-character console window.
SIMP-5932 #close
> (SIMP-5932) Add puppetserver wait option to bootstrap

- build/rubygem-simp-cli.spec
- lib/simp/cli/commands/bootstrap.rb
- lib/simp/cli/version.rb
The subsequent processing for `info()` strings would try to interpolate
variables if set which caused an out of scope variable call if simp
bootstrap is run after already having successfully run.
> (SIMP-MAINT) Fix info() call

- build/rubygem-simp-cli.spec
- lib/simp/cli/commands/bootstrap.rb
Fixed a bug where the web-routes.conf file was not being overwritten
with a pristine copy. This meant that multiple calls to `simp bootstrap`
would fail due to leftover CA entries in the file. The error provided is
not clear and has been provided upstream to Puppet, Inc.
> (SIMP-MAINT) Fix issue with multiple bootstrap runs

- build/rubygem-simp-cli.spec
- lib/simp/cli/config/items/action/create_simp_server_fqdn_yaml_action.rb
Fixed file path for @alt_file, and added code to list existing <host>.yaml files to the debug() log.
> SIMP-6205 simp config fails template copy when hostname is changed

- lib/simp/cli/commands/bootstrap.rb
Bootstrap has been failing on my systems (RedHat, SIMP EE 6.3) due to the fact that the puppetserver is never reloaded after the port changes to 8140. This adds a reload after the first puppet run so the puppetserver actually restarts and comes up successfully on the correct port.
> Allow simp bootstrap to complete successfully

- .travis.yml
- build/rubygem-simp-cli.spec
- lib/simp/cli/commands/bootstrap.rb
Added message to bootstrap.rb indicating that puppetserver has been
reconfigured to listen on a specific port. This message will be
displayed if the port is changed to 8140, or if it remains on 8150.
> (SIMP-5156) Added message regarding puppetserver port change

- build/rubygem-simp-cli.spec
- lib/simp/cli/commands/bootstrap.rb
The cleanup of the %post sections of the SIMP asset RPMs
now requires `simp bootstrap` to execute more than 1 tagged
run on the bootstrap port.
The specific problem was the permissions on
/opt/puppetlabs/puppet/cache/pdb_tmp.
SIMP-6628
> (SIMP-6628) simp bootstrap:2 tagged runs required

- build/rubygem-simp-cli.spec
- lib/simp/cli/config/items/action/answers_yaml_file_writer.rb
- spec/lib/simp/cli/config/items/action/files/answers_yaml_file_writer.yaml
Disable marking entries as 'automatically set' in the answers
YAML file as this notation is incorrect when an answers file
is used as input to 'simp config'.
SIMP-6622 #close
> (SIMP-6622) simp config automatic setting message incorrect

- lib/simp/cli/commands/config.rb
- lib/simp/cli/config/items/data/simp_options_dns_servers.rb
- lib/simp/cli/logging.rb
- spec/lib/simp/cli/logging_spec.rb
- Warn user to backup their Puppet environment prior
to running `simp config --force-config` on an existing
SIMP omni-environment
- Specify the full simp command required for --force-config
- Fix bad description for simp_options::dns::servers
- Don't fail `simp config` because of an existing SIMP
omni-environment, when the user is continuing an interrupted
session (a session in which at least *one* configuration value
was gathered from the user).  `simp config` will still fail a
subsequent run if the user didn't enter the questionnaire but
*did* allow the SIMP omni-environment to be created....Fixing
this specific case requires a bigger structural change to the code.
SIMP-6544 #close
SIMP-6632 #close
> (SIMP-6632) Warn on simp config --force-config

- build/rubygem-simp-cli.spec
- lib/simp/cli.rb
- lib/simp/cli/commands/bootstrap.rb
- lib/simp/cli/commands/command.rb
- lib/simp/cli/commands/config.rb
- lib/simp/cli/commands/doc.rb
- lib/simp/cli/commands/passgen.rb
- lib/simp/cli/commands/version.rb
- spec/bin/simp_spec.rb
- spec/lib/simp/cli/commands/doc_spec.rb
- spec/lib/simp/cli/commands/version_spec.rb
- spec/lib/simp/cli_spec.rb
- Standardized top level help
- Replaced 'simp help command', with 'simp -h', because the
help command mechanism was not supported by subcommands
which made the help API confusing
- Created version command and added -h option to it
- Added -h option to doc command
- Added brief descriptions to top level help
> (SIMP-MAINT) Improve top level help

- build/rubygem-simp-cli.spec
- lib/simp/cli/commands/config.rb
- lib/simp/cli/config/simp_puppet_env_helper.rb
- lib/simp/cli/environment/secondary_dir_env.rb
- spec/lib/simp/cli/config/simp_puppet_env_helper_spec.rb
Workaround an issue in which the example, empty production
Puppet environment that is installed by the puppet-agent
RPM causes the OmniEnvController#create to fail.
SIMP-6661 #close
> (SIMP-6661) Handle existing example production env

- build/rubygem-simp-cli.spec
- lib/simp/cli/command_logger.rb
- lib/simp/cli/commands/environment/fix.rb
- lib/simp/cli/commands/environment/new.rb
- lib/simp/cli/config/items/action/configure_network_action.rb
- lib/simp/cli/config/items/action_item.rb
- lib/simp/cli/environment/dir_env.rb
- lib/simp/cli/environment/env.rb
- lib/simp/cli/environment/omni_env_controller.rb
- lib/simp/cli/environment/puppet_dir_env.rb
- lib/simp/cli/environment/secondary_dir_env.rb
- lib/simp/cli/environment/writable_dir_env.rb
- spec/lib/simp/cli/command_logger_spec.rb
- spec/lib/simp/cli/commands/environment/fix_spec.rb
- spec/lib/simp/cli/commands/environment/new_spec.rb
- spec/lib/simp/cli/config/items/action/configure_network_action_spec.rb
- spec/lib/simp/cli/config/items/action/set_grub_password_action_spec.rb
- spec/lib/simp/cli/environment/dir_env_spec.rb
- spec/lib/simp/cli/environment/omni_env_controller_spec.rb
- spec/lib/simp/cli/environment/puppet_dir_env_spec.rb
- spec/lib/simp/cli/environment/secondary_dir_env_spec.rb
- spec/lib/simp/cli/environment/writable_dir_env_spec.rb
- spec/lib/simp/cli/puppetfile/local_simp_puppet_modules_spec.rb
`simp environment new` changes:
- Behaviors match `--help` documentation:
- `--skeleton` implies `--puppetfile`
- `--puppetfile`:
- generates `Puppetfile.simp` from local RPM/git repos
- generates a skeleton `Puppetfile` (if needed)
- Fails before acting if any component environment cannot be created
SIMP-6662 #comment --puppetfile creates Puppetfile and Puppetfile.simp
SIMP-6662 #comment --skeleton implies --puppetfile
SIMP-6662 #close
SIMP-6663 #comment checks entire omni env before creating new envs
SIMP-6663 #close
> (SIMP-6662) simp env new behavior matches `--help`

- lib/simp/cli/commands/puppetfile/generate.rb
- lib/simp/cli/puppetfile/skeleton.rb
- spec/lib/simp/cli/commands/puppetfile/generate_spec.rb
- spec/lib/simp/cli/puppetfile/files/malformed_metadata/metadata.json
- spec/lib/simp/cli/puppetfile/files/missing_name_metadata/metadata.json
- spec/lib/simp/cli/puppetfile/files/saz-timezone/metadata.json
- spec/lib/simp/cli/puppetfile/files/simp-timezone/metadata.json
- spec/lib/simp/cli/puppetfile/skeleton_spec.rb
`simp puppetfile generate --skeleton --local-modules ENV` now
excludes any local modules found in the specified environment for
which a local, SIMP-managed repo exists.
SIMP-6681 #comment rubygem-simp-cli
> (SIMP-6681) simp puppetfile generate does not support upgrades

- build/rubygem-simp-cli.spec
- lib/simp/cli/environment/secondary_dir_env.rb
- lib/simp/cli/version.rb
Contents of linux-install/centos-7-x86_64 should be world readable
SIMP-6828 #close
> (SIMP-6828) Fix Secondary Environment for TFTP server

- .gitignore
- Rakefile
- lib/simp/cli/commands/passgen.rb
- lib/simp/cli/passgen/utils.rb
- spec/acceptance/shared_examples/simp_asset_manual_install.rb
- spec/lib/simp/cli/commands/passgen_spec.rb
- spec/lib/simp/cli/passgen/utils_spec.rb
Fixed a 'simp passgen' bug in which it accepted an empty
password and then failed with an error message that was
meaningless to the user, when it attempted to set the
password via a 'puppet apply'.
* When libpwquality/cracklib validation is disabled, a user
entered password is now validated for length prior to
attempting to use it.
* Retooled simp-cli and highline gem installation to ensure
the correct version of highline is used by simp-cli.
The previous (hacked) install method resulted in the older
version of highline packaged with puppet-agent being
used, instead.
> (SIMP-7244) simp passgen prevent empty passwords

- build/rubygem-simp-cli.spec
- lib/simp/cli/config/questionnaire.rb
- Fixed an issue where --dry-run would prompt the user to apply instead of
simply skipping to the (skipped) action items and then writing the
~/.simp/simp_conf.yaml file
SIMP-7533 #close
> (SIMP-7533) Fix --dry-run issue with simp_conf.yaml

- build/rubygem-simp-cli.spec
- lib/simp/cli/config/items/action/hieradata_yaml_file_writer.rb
- lib/simp/cli/config/items/action/warn_lockout_risk_action.rb
- lib/simp/cli/config/items/add_server_class_action_item.rb
- lib/simp/cli/config/items/set_server_hieradata_action_item.rb
- spec/lib/simp/cli/commands/files/environments/simp/data/hosts/puppet.your.domain.yaml
- spec/lib/simp/cli/commands/files/environments/simp_hiera3/hieradata/scenarios/simp_lite.yaml
- spec/lib/simp/cli/config/items/action/files/hieradata_yaml_file_writer_with_classes.yaml
- spec/lib/simp/cli/config/items/action/hieradata_yaml_file_writer_spec.rb
* Ensure that `simp config` can handle the following in Hiera (in this
priority order):
* simp::server::classes
* simp::classes
* classes
* Ensure that the default output to the configuration file is
`simp::classes` since it is meant to apply to all hosts by default.
* This change was tested via the `Vagrantfile` in `simp-core` and manual
application.
SIMP-6822 #close
> [SIMP-6822] Migrate away from global 'classes'

- build/rubygem-simp-cli.spec
- lib/simp/cli/commands/bootstrap.rb
- lib/simp/cli/defaults.rb
Allow users to set the SIMP_ENVIRONMENT environment variable to change
the initial environment from 'production' to a custom value
SIMP-6936 #comment Partial fix for setting the initial SIMP environment
> (SIMP-6936) Partial fix for setting initial env

- Rakefile
- build/rubygem-simp-cli.spec
- lib/simp/cli/version.rb
- The Rake file attempts to clear out task spec_standalone but when building
the ISO in rpm_docker this task, predefined by puppet, is
not defined.  So check if the task is defined before trying
to clear it
SIMP-8075 #comment   rubygem-simp-cli
> (SIMP-8075)  Rake task not working

- build/rubygem-simp-cli.spec
- lib/simp/cli/commands/bootstrap.rb
- lib/simp/cli/commands/config.rb
- lib/simp/cli/version.rb
- spec/bin/files/simp_config_full_stdin_file
- spec/lib/simp/cli/commands/config_spec_helper.rb
- spec/lib/simp/cli/config/items/action_item_spec.rb
- Fixed a typo in an error message emitted when 'simp config' cannot
proceed because the environment to configure already exists.
- Fixed stream input used in 'simp config' unit tests. The streams had
extraneous, unread characters that should have been removed in an
earlier dry-run-related bug fix.
SIMP-8380 #close
> (SIMP-8380) Fix typo in CLI error message

- .gitlab-ci.yml
- Gemfile
- Rakefile
- build/rubygem-simp-cli.spec
- lib/simp/cli/environment/secondary_dir_env.rb
- spec/acceptance/helpers/beaker_workarounds.rb
- spec/acceptance/shared_examples/workaround_beaker_connectivity.rb
- spec/acceptance/suites/default/00_simp_passgen_set_up_spec.rb
- spec/acceptance/suites/default/01_simp_passgen_list_ops_spec.rb
- spec/acceptance/suites/default/02_simp_passgen_modify_passwords_spec.rb
- spec/acceptance/suites/default/03_simp_passgen_create_remove_passwords_spec.rb
- spec/acceptance/suites/default/04_simp_passgen_misc_spec.rb
- spec/acceptance/suites/simp_kv/00_simp_cli_set_up_spec.rb
- spec/acceptance/suites/simp_kv/01_simp_kv_set_up_spec.rb
- spec/acceptance/suites/simp_kv/10_simp_kv_exists_ops_spec.rb
- spec/acceptance/suites/simp_kv/20_simp_kv_list_ops_spec.rb
- spec/acceptance/suites/simp_kv/30_simp_kv_get_ops_spec.rb
- spec/acceptance/suites/simp_kv/40_simp_kv_put_ops_spec.rb
- spec/acceptance/suites/simp_kv/50_simp_kv_delete_ops_spec.rb
- spec/acceptance/suites/simp_kv/60_simp_kv_deletetree_ops_spec.rb
- spec/acceptance/suites/simp_kv/70_simp_kv_errors_spec.rb
- spec/spec_helper_acceptance.rb
* Fixed a bug in `simp environment new` in which the actual failure
messages from a failed `setfacl --restore` execution are not logged.
* The underlying `execute()` function will capture and log the
error messages when the command fails.
* Restructured acceptance tests to try to workaround beaker random
ssh disconnects on slow GitLab servers.
* These workarounds don't solve the problem, but reduce it.
* Need beaker support to set ssh keepalive settings to solve the
problem.
* Temporarily disabled FIPS-mode acceptance tests until the local HighLine
gem can be updated to version >= 2.0.0.
* Bundler will fail with the version of simp-beaker-helpers required
to fix the FIPS-mode setup bug. (See SIMP-8406).
* The tests can take more than an hour to fail.
* Added support for Bundler 2.x and …
> (SIMP-7238) simp environment new hides actual FACL failure

- Gemfile
- build/rubygem-simp-cli.spec
- lib/simp/cli/config/items/data/sssd_domains.rb
- lib/simp/cli/version.rb
- spec/acceptance/nodesets/default.yml
- spec/lib/simp/cli/commands/config_run_spec.rb
- spec/lib/simp/cli/commands/config_spec_helper.rb
- spec/lib/simp/cli/config/items/action/set_hostname_action_spec.rb
- spec/lib/simp/cli/config/items/action/update_os_yum_repositories_action_spec.rb
- spec/lib/simp/cli/config/items/data/sssd_domains_spec.rb
- spec/lib/simp/cli/config/simp_puppet_env_helper_spec.rb
- Fixed a bug where 'simp config' recommended the wrong SSSD domain,
when the SIMP server was not the LDAP server.  It recommended the
'Local' domain, when the appropriate SIMP-created domain with the
'local' (EL6) or 'files' (EL7) provider is 'LOCAL'.
- Fixed bad changelog entry.
- Cleaned up a few unit tests
- Mocked out a `hostname` system call in a spec test, instead of
expecting the actual `hostname` operation to fail.
- Mocked out File.exist?('/etc/yum.repos.d/simp_filesystem.repo')
calls instead of assuming it will always return false.
- Mocked out 'chown -R root:apache ...' system calls in spec tests.
- Removed extraneous tests that were failing because of
'chown -R root:apache' failures, instead of what the test was
hoping to test. I didn't bother to fix the tests with mock …
> (SIMP-8383) simp cli uses wrong local sssd domain

- .gitlab-ci.yml
- .travis.yml
- Gemfile
- build/rubygem-simp-cli.spec
- lib/simp/cli/version.rb
- simp-cli.gemspec
This patch removes ALL TESTS from the Travis CI pipeline.
It also updates the .gemspec to mitigate CVE-2020-8130.
[SIMP-8802] #close
[SIMP-8802]: https://simp-project.atlassian.net/browse/SIMP-8802
> (SIMP-8802) Remove Travis CI tests

- .github/workflows/pr_tests.yml
- lib/simp/cli/config/items/data/sssd_domains.rb
- spec/acceptance/shared_examples/fixtures_move.rb
- spec/lib/simp/cli/config/items/data/sssd_domains_spec.rb
- Fixed a bug where sssd::domains validation did not allow an
empty domain list in EL8, even though it recommended an empty
domain list.
- Removed EL6-specific test logic that no longer applies, as
simp-rsync-skeleton no longer installs those directories.
SIMP-9378 #close
> (SIMP-9378) simp-cli: allow empty domain list EL8

- build/rubygem-simp-cli.spec
- lib/simp/cli/config/items/data/chrony_servers.rb
- lib/simp/cli/config/items/data/chronyd_link_to_ntpservers.rb
- lib/simp/cli/config/items/data/simp_options_ntp_servers.rb
- lib/simp/cli/config/scenarios/parts/network_setup
- lib/simp/cli/utils.rb
- lib/simp/cli/version.rb
- spec/lib/simp/cli/commands/config_run_spec.rb
- spec/lib/simp/cli/commands/config_spec_helper.rb
- spec/lib/simp/cli/commands/files/incomplete_prev_simp_conf.yaml
- spec/lib/simp/cli/commands/files/prev_simp_conf.yaml
- spec/lib/simp/cli/commands/files/prev_simp_conf_invalid_interface.yaml
- spec/lib/simp/cli/commands/files/simp_conf_accepting_defaults_simp_scenario.yaml
- spec/lib/simp/cli/commands/files/simp_conf_missing_scenario.yaml
- spec/lib/simp/cli/commands/files/simp_conf_setting_values_poss_scenario.yaml
- spec/lib/simp/cli/commands/files/simp_conf_setting_values_simp_lite_scenario.yaml
- spec/lib/simp/cli/commands/files/simp_conf_with_overrides.yaml
- spec/lib/simp/cli/config/files/poss_generated_items_tree.yaml
- spec/lib/simp/cli/config/files/simp_generated_items_tree.yaml
- spec/lib/simp/cli/config/files/simp_lite_generated_items_tree.yaml
- spec/lib/simp/cli/config/items/data/files/chrony.conf_local_servers
- spec/lib/simp/cli/config/items/data/files/chrony.conf_no_servers
- spec/lib/simp/cli/config/items/data/files/chrony.conf_remote_servers
- spec/lib/simp/cli/config/items/data/files/ntp.conf_remote_servers
- spec/lib/simp/cli/config/items/data/simp_options_ntp_servers_spec.rb
- Add item in network task list to create a hiera link from
chronyd::servers to simp_options::ntp::servers.
- Update `simp config` to check for chrony settings
when determining the currently set os value.
SIMP-7465 #close
SIMP-8966 #close
> (SIMP-7465) Update to handle chronyd default

- .gitignore
- .gitlab-ci.yml
- lib/simp/cli/commands/bootstrap.rb
- lib/simp/cli/config/items/list_item.rb
- spec/acceptance/shared_examples/configure_puppet_env.rb
- spec/lib/simp/cli/config/items/list_item_spec.rb
- Fixed an internal simp config bug that was causing the non-interactive
default value for sssd:domains to be incorrectly determined on EL8.
- Removed the OBE and ignored HTTP Accept header in the curl command used
by `simp bootstrap` to determine if the puppetserver is up.
- Fixed the test command used to determine if the puppetserver was up.
- The unversioned `python` command is not available on EL8. So,
reworked the command to match that used by `simp bootstrap`.
- Re-enabled EL8 tests in GitLab.
SIMP-9621 #close
> (SIMP-9621) simp cli tests fail on EL8

- .gitlab-ci.yml
- spec/acceptance/nodesets/centos8.yml
- spec/acceptance/nodesets/default.yml
- spec/acceptance/shared_examples/configure_puppet_env.rb
- spec/acceptance/shared_examples/fixtures_move.rb
- spec/acceptance/shared_examples/kv_test_envs_set_up.rb
- spec/acceptance/shared_examples/passgen_test_envs_set_up.rb
- spec/acceptance/shared_examples/puppetserver_set_up.rb
- spec/acceptance/shared_examples/simp_asset_manual_install.rb
- spec/acceptance/shared_examples/simp_module_git_repos_manual_install.rb
- spec/acceptance/suites/default/00_simp_passgen_set_up_spec.rb
- spec/acceptance/suites/simp_kv/00_simp_cli_set_up_spec.rb
- spec/lib/simp/cli/config/items/action/update_os_yum_repositories_action_spec.rb
- spec/spec_helper_acceptance.rb
* Maintenance
- Test with CentOS 8.4 via generic/centos8 box
- Updated .gitlab-ci.yml to be closer to Puppet module asset
- Reworked spec test so that SIMP_SKIP_NON_SIMPOS_TESTS environment
variable is not necessary. Eliminates one customization in
.gitlab-ci.yml.
- Fail acceptance tests if no examples are executed.
- Replaced most uses of 'master' with 'server' in acceptance tests.
SIMP-10255 #close
[SIMP-9666] #comment rubygem-simp-cli acceptance tests configured
[SIMP-9666]: https://simp-project.atlassian.net/browse/SIMP-9666
> (SIMP-10255) rubygem-simp-cli Ensure testing with CentOS 8.4

- build/rubygem-simp-cli.spec
- simp-cli.gemspec
Before this patch, the project's RPM .spec file used a hard-coded
`Release:` number that could not be overridden by the optional
`build/rpm_metadata/release` file used by other projects.
This patch adds support for `build/rpm_metadata/release`, and defaults
to the standard `-1` Release value.
[SIMP-10415] #comment Update rubygem-simp-cli
[SIMP-10416] #close
[SIMP-10415]: https://simp-project.atlassian.net/browse/SIMP-10415
[SIMP-10416]: https://simp-project.atlassian.net/browse/SIMP-10416
> (SIMP-10415) Honor build/rpm_metadata/requires

- .gitlab-ci.yml
- build/rubygem-simp-cli.spec
- lib/simp/cli/commands/bootstrap.rb
- lib/simp/cli/commands/passgen/envs.rb
- lib/simp/cli/utils.rb
- spec/acceptance/shared_examples/configure_puppet_env.rb
- Changed the check for puppetserver running from a fragile CRL query to the
actual `status` endpoint and moved from `curl` to native `net/http`
- Changed set/get from `master` to `server` in updates to the puppet
configuration
SIMP-10025 #close
> (SIMP-10025) Bootstrap server status fix

- build/rubygem-simp-cli.spec
- lib/simp/cli/config/items/data/simp_options_dns_search.rb
- lib/simp/cli/config/items/data/simp_options_dns_servers.rb
- spec/lib/simp/cli/config/items/data/simp_options_dns_search_spec.rb
- spec/lib/simp/cli/config/items/data/simp_options_dns_servers_spec.rb
Updated the logic that extracts existing DNS configuration to
handle scenarios in which /etc/resolv.conf is not available.
- Non-existent /etc/resolv.conf was seen with SIMP 6.6.0 Alpha system
installed via ISO (EFI) for EL8
SIMP-10583 #close
> (SIMP-10583) simp config fails when /etc/resolv.conf missing EL8

- .github/workflows/release_rpms.yml
- .github/workflows/tag_deploy_rubygem__github-rpms.yml
- .github/workflows/validate_tokens_asset.yml
This commit rolls up various improvements to the GHA tag & release
workflows, particularly:
* Tagged releases build a matrix of RPMs: (EL8 *and* EL7)
* Tagged release logic supports pre/post-release tag formats
* New arguments in `release_rpms.yml`: `path_to_build` and `verbose`
* Ensure jobs run on `ubuntu-latest`
* Fixes for variable edge cases and inter-job dependencies
and may apply other updates to ensure conformity.
[SIMP-10646] #close
[SIMP-10633] #comment Add `release_rpms` to rubygem-simp-cli
[SIMP-10646]: https://simp-project.atlassian.net/browse/SIMP-10646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SIMP-10633]: …
> (SIMP-10633) Update standardized assets

- .github/workflows/pr_glci.yml
- .github/workflows/pr_glci_cleanup.yml
- .github/workflows/pr_glci_manual.yml
- .github/workflows/release_rpms.yml
- .github/workflows/tag_deploy_rubygem__github-rpms.yml
- .github/workflows/validate_tokens_asset.yml
This patch updates GHA workflows to use GCP as a hypervisor when
BEAKER_HYPERVISOR is `google`
and may also apply other updates to ensure conformity.
> Add GCP support to GLCI

- .github/workflows/add_new_issue_to_triage_project.yml
- .github/workflows/tag_deploy_rubygem__github-rpms.yml
and may also apply other updates to ensure conformity.
> Add GHA action to add new issues to triage project

- .github/workflows/tag_deploy_rubygem__github-rpms.yml
* Replace deprecated create-release@v1 
* Convert the remaining ::set-output GHA workflows
and may also apply other updates to ensure conformity.
> GHA workflow deprecations updates

- .gitlab-ci.yml
- Gemfile
:warning: This was a PoC hand-edited change from 20230501
This patch moves puppet 6 refs to 7, puppet 7 refs to 8 and comments 
out the puppet 8 and oel refs in the "repo specific content" section.
and may also apply other updates to ensure conformity.
> Remove puppet 6 from .gitlab-ci.yml

- .github/workflows/pr_tests.yml
- .rubocop.yml
- Gemfile
- lib/simp/cli/commands/bootstrap.rb
- lib/simp/cli/commands/doc.rb
- lib/simp/cli/config/items/action/create_simp_server_fqdn_yaml_action.rb
- lib/simp/cli/config/items/action/set_site_scenario_action.rb
- lib/simp/cli/config/items/data/simp_options_ldap_master.rb
- lib/simp/cli/config/items/data/simp_options_ldap_uri.rb
- lib/simp/cli/config/items/data/simp_options_ntp_servers.rb
- lib/simp/cli/config/items/yes_no_item.rb
- lib/simp/cli/config/utils.rb
- lib/simp/cli/environment/puppet_dir_env.rb
- simp-cli.gemspec
- spec/bin/simp_spec.rb
- spec/lib/simp/cli/commands/config_read_answers_file_spec.rb
- spec/lib/simp/cli/config/items/action/answers_yaml_file_writer_spec.rb
- spec/lib/simp/cli/config/items/action/generate_certificates_action_spec.rb
- spec/lib/simp/cli/config/yaml_utils_spec.rb
* Various fixes for Ruby 3 compatibility
* Update rubocop configuration
* Clean up Gemfile for rubocop
* Update gem dependencies
* Use Ruby 2.7 for GHA and add Puppet 8 to test matrix
Closes #192
> Updates for Ruby 3
