simp/rubygem-simp-cli

.travis.yml
=> (SIMP-115) Fix nil Utils.validate_password tests

build/rubygem-simp-cli.el6.spec, build/rubygem-simp-cli.el7.spec
So version, much bad.
SIMP-47 #comment RPM spec correction to account for gem version bump
=> (SIMP-47) Corrected the RPM spec files

build/rubygem-simp-cli.el6.spec, build/rubygem-simp-cli.el7.spec
Bumped the spec files to match cli.rb so rpm builds work.
SIMP-17 #comment Bump simp-cli spec
=> (SIMP-17) Fix simp-cli ldap spec update

build/rubygem-simp-cli.el6.spec, build/rubygem-simp-cli.el7.spec, lib/simp/cli.rb, lib/simp/cli/commands/bootstrap.rb
A full relabel needs to happen before selinux is fully enabled.
SIMP-401 #comment Run fixfiles
=> (SIMP-401) Run fixfiles before finalization bootstrap runs.

build/rubygem-simp-cli.el6.spec, build/rubygem-simp-cli.el7.spec, lib/simp/cli.rb, lib/simp/cli/config/item/puppet_conf.rb, spec/lib/simp/cli/config/item/puppet_conf_spec.rb
Ensure that keylength is set to 2048 if FIPS is enabled.
SIMP-461 #close
=> (SIMP-461) 'simp config' needs to set the proper keylength for FIPS

lib/simp/cli/commands/config.rb
Before this patch, `simp config` did not have access to any custom facts
prior to a pluginsync, with the exception of a hardcoded path to
simp-common (assuming the modules were installed by a SIMP ISO.
This patch finds all modules and makes their custom facts available to
`simp config` prior to the execution of any Config::Items.
SIMP-509 #close #comment Enabled all custom facts in `simp config`
=> (SIMP-509) Enable all custom facts in simp config

simp-cli.gemspec
=> (SIMP-554)  Require 'date' in simp-cli.gemspec

spec/lib/simp/cli/config/item/enable_simp_repos_spec.rb, spec/lib/simp/cli/config/item/is_master_yum_server_spec.rb
SIMP-565 #comment Added spec tests for simp::yum::enable_simp_repos
SIMP-565 #comment Added spec tests for simp::yum::is_master_yum_server
=> (SIMP-565) Add spec tests for previous commit

lib/simp/cli/commands/config.rb
=> (SIMP-597) Erroneous commas in simp config.

build/rubygem-simp-cli.el6.spec, build/rubygem-simp-cli.el7.spec
SIMP-624 #comment Bumped RPM version to 1.0.13-0
=> (SIMP-624) Bump RPM version to 1.0.13-0

build/rubygem-simp-cli.el6.spec, build/rubygem-simp-cli.el7.spec, lib/simp/cli.rb, lib/simp/cli/config/item/sssd_domains.rb, lib/simp/cli/config/item_list_factory.rb, spec/lib/simp/cli/config/item/sssd_domains_spec.rb
SIMP-640 #comment Added `sssd::domains` item
SIMP-640 #comment `sssd::domains` includes 'LDAP' when `use_ldap`==true
SIMP-640 #close #comment Bumped package versions to 1.0.14-0.
=> (SIMP-640) Add `sssd::domains` to match `use_ldap`

build/rubygem-simp-cli.el6.spec, build/rubygem-simp-cli.el7.spec
RPM spec file update
SIMP-612 #comment update for rpm spec
=> (SIMP-612) CLI update for RPM

build/rubygem-simp-cli.el6.spec, build/rubygem-simp-cli.el7.spec
The RPM spec files needed to be updated
SIMP-1165 #comment bump the RPM version
=> (SIMP-1165) Version bump in RPM

build/rubygem-simp-cli.spec, lib/simp/cli/commands/bootstrap.rb
- Modified bootstrap to include a pupmod tag, and optimized
it for SIMP-6.
SIMP-2700 #close
=> (SIMP-2700) Optimized bootstrap for SIMP-6

build/rubygem-simp-cli.spec, lib/simp/cli/lib/utils.rb
=> (SIMP-2968) Update location of FakeCA used by simp cli

build/rubygem-simp-cli.spec, lib/simp/cli/commands/bootstrap.rb, lib/simp/cli/version.rb
=> (SIMP-3278) Back up and remove /etc/puppetlabs/puppet/auth.conf

.travis.yml
Add 'release on github' deploy step, when the repo is tagged
=> (SIMP-3291) simp-cli: Configure Travis to release

build/rubygem-simp-cli.spec, lib/simp/cli/config/items/data/simp_options_ntp_servers.rb, lib/simp/cli/config/items/data/simp_options_syslog_failover_log_servers.rb, lib/simp/cli/config/items/data/simp_options_syslog_log_servers.rb, lib/simp/cli/config/utils.rb, spec/lib/simp/cli/config/items/data/cli_network_hostname_spec.rb, spec/lib/simp/cli/config/items/data/simp_options_dns_search_spec.rb, spec/lib/simp/cli/config/items/data/simp_options_ldap_master_spec.rb, spec/lib/simp/cli/config/items/data/simp_options_ntp_servers_spec.rb, spec/lib/simp/cli/config/items/data/simp_options_syslog_failover_log_servers_spec.rb, spec/lib/simp/cli/config/items/data/simp_options_syslog_log_servers_spec.rb, spec/lib/simp/cli/config/items/data/simp_yum_repo_local_os_updates_servers_spec.rb, spec/lib/simp/cli/config/items/data/simp_yum_repo_local_simp_servers_spec.rb, spec/lib/simp/cli/config/utils_spec.rb
SIMP-3666 #close
SIMP-3667 #close
SIMP-3668 #close
SIMP-3630 #close
=> (SIMP-3666) simp-cli:  Fails to validate complex hostnames

lib/simp/cli/version.rb
version.rb must match  version in rubygem-simp-cli.spec
SIMP-3851 #comment fix version
=> (SIMP-3851) simp-cli: Fix version in version.rb

build/rubygem-simp-cli.spec, spec/lib/simp/cli/commands/files/environments/simp/hieradata/scenarios/simp.yaml, spec/lib/simp/cli/commands/files/environments/simp/hieradata/scenarios/simp_lite.yaml
- removed simp_options::selinux from test data.
SIMP-3858 #comment updated simp-cli tests
SIMP-4528 #close
=> (SIMP-3858) Remove simp_options::selinux

.rspec, Gemfile, bin/simp, build/rubygem-simp-cli.spec, lib/simp/cli/commands/bootstrap.rb, lib/simp/cli/config/items/action/update_puppet_conf_action.rb, lib/simp/cli/config/items/action/warn_client_yum_config_action.rb, lib/simp/cli/config/items/class_item.rb, lib/simp/cli/config/items/data/simp_options_puppet_ca_port.rb, lib/simp/cli/config/items/item.rb, lib/simp/cli/config/scenarios/parts/yum_setup, lib/simp/cli/utils.rb, lib/simp/cli/version.rb, spec/lib/simp/cli/config/files/poss_generated_items_tree.yaml, spec/lib/simp/cli/config/files/simp_generated_items_tree.yaml, spec/lib/simp/cli/config/files/simp_lite_generated_items_tree.yaml, spec/lib/simp/cli/config/items/action/configure_network_action_spec.rb, spec/lib/simp/cli/config/items/action/set_hostname_action_spec.rb, spec/lib/simp/cli/config/items/action/set_puppet_digest_algorithm_action_spec.rb, spec/lib/simp/cli/config/items/action/update_puppet_conf_action_spec.rb, spec/lib/simp/cli/config/items/data/simp_options_puppet_ca_port_spec.rb
* Stripped trailing whitespace
* Adjusted bootstrap to detect PE and avoid operations that are
detrimental to proper operation
* Made a few adjustments for overall safety
* Fixed dependency loading for 'highline/import' by clearing the gem
cache
SIMP-4003 #comment simp-boostrap updates
=> (SIMP-3993) Updates to work with PE

build/rubygem-simp-cli.spec, lib/simp/cli/version.rb
- added pupmod-simp-network as a dependency
SIMP-5539 #comment this is need for ISO building simp-core
=> (SIMP-5539) Update dependencies for simp-cli

build/rubygem-simp-cli.spec, lib/simp/cli/version.rb
- tests not passing because of bad changelog date in simp cli
SIMP-5872 #comment
=> SIMP-5872 Fix  changelog date in simp cli

lib/simp/cli/commands/bootstrap.rb
* Ensure that we don't drop a random file named 'echo' on the system
* Remove usage of 'simp_file_line' since we don't actually know what
environment we are using at this point and the module path may not
have this function loaded.
=> (SIMP-MAINT) Java related cleanup

README.md
=> (SIMP-6208) Update README with puppetfile generate

.rubocop.yml, Gemfile, build/rubygem-simp-cli.spec, lib/simp/cli/commands/bootstrap.rb, lib/simp/cli/commands/command_family.rb, lib/simp/cli/commands/environment.rb, lib/simp/cli/commands/environment/fix.rb, lib/simp/cli/commands/environment/new.rb, lib/simp/cli/commands/puppetfile.rb, lib/simp/cli/config/simp_puppet_env_helper.rb, lib/simp/cli/environment/dir_env.rb, lib/simp/cli/environment/env.rb, lib/simp/cli/environment/omni_env_controller.rb, lib/simp/cli/environment/puppet_dir_env.rb, lib/simp/cli/environment/secondary_dir_env.rb, lib/simp/cli/environment/writable_dir_env.rb, lib/simp/cli/utils.rb, spec/bin/simp_spec.rb, spec/lib/simp/cli/commands/environment/fix_spec.rb, spec/lib/simp/cli/commands/environment/new_spec.rb, spec/lib/simp/cli/environment/dir_env_spec.rb, spec/lib/simp/cli/environment/env_spec.rb, spec/lib/simp/cli/environment/files/omni_env_controller_opts.yaml, spec/lib/simp/cli/environment/omni_env_controller_spec.rb, spec/lib/simp/cli/environment/puppet_dir_env_spec.rb, spec/lib/simp/cli/environment/secondary_dir_env_spec.rb, spec/lib/simp/cli/environment/writable_dir_env_spec.rb, spec/lib/simp/cli_spec.rb, spec/spec_helper.rb
This patch implements #fix and #new logic
SIMP-6408 #close
SIMP-6416 #close #comment Puppet env dir .fix
SIMP-6417 #close #comment Secondary env dir .fix
SIMP-6418 #close #comment Puppet env dir .new
SIMP-6419 #close #comment Secondary env dir .new
SIMP-6421 #close #comment Writable env dir .new
=> (SIMP-6408) Implement initial #fix and #new logic

lib/simp/cli/commands/bootstrap.rb
Hardcoding the number of tagged runs caused bootstrap
to fail when it was rerun, because only 1 run is required
the second time around. To fix this problem, replaced the
hardcoded number of tagged runs with logic to ensure
bootstrap only executes these runs up to the point the
puppetserver is no longer running on the bootstrap port.
SIMP-6704 #close
=> (SIMP-6704) bootstrap cannot be rerun

build/rubygem-simp-cli.spec, lib/simp/cli/config/items/action/warn_lockout_risk_action.rb
=> (SIMP-6864) Possible root lockout instructions incomplete

build/rubygem-simp-cli.spec, lib/simp/cli/config/items/action/warn_lockout_risk_action.rb, lib/simp/cli/version.rb
=> (SIMP-6864) Fix errata in lockout prevention instructions

lib/simp/cli/config/items/action/warn_lockout_risk_action.rb
Fixed:
* Aligned the lockout file content with the new version from simp-doc
SIMP-8454 #close
=> (SIMP-8454) Fix lockout risk warning file

build/rubygem-simp-cli.spec, lib/simp/cli/config/items/action/warn_lockout_risk_action.rb, lib/simp/cli/version.rb
Fixed:
* Replaced the module creation, etc... with a short YAML snippet
SIMP-8574 #close
=> (SIMP-8572) Refactor the lockout docs

lib/simp/cli/config/items/action/warn_lockout_risk_action.rb
Changed:
* Tweaked local user access to only affect the SIMP server
[SIMP-8572] #close
[SIMP-8572]: https://simp-project.atlassian.net/browse/SIMP-8572
=> (SIMP-8572) Change the SIMP server, not default

.gitlab-ci.yml, build/rubygem-simp-cli.spec, lib/simp/cli/config/items/action/set_grub_password_action.rb, lib/simp/cli/config/items/data/grub_password.rb, lib/simp/cli/config/items/data/simp_run_level.rb, lib/simp/cli/config/items/data/sssd_domains.rb, spec/acceptance/helpers/beaker_workarounds.rb, spec/acceptance/nodesets/default.yml, spec/acceptance/shared_examples/configure_puppet_env.rb, spec/acceptance/shared_examples/fixtures_move.rb, spec/lib/simp/cli/commands/config_run_spec.rb, spec/lib/simp/cli/commands/files/incomplete_prev_simp_conf.yaml, spec/lib/simp/cli/commands/files/prev_simp_conf.yaml, spec/lib/simp/cli/commands/files/prev_simp_conf_invalid_interface.yaml, spec/lib/simp/cli/commands/files/simp_conf_accepting_defaults_simp_scenario.yaml, spec/lib/simp/cli/commands/files/simp_conf_missing_scenario.yaml, spec/lib/simp/cli/commands/files/simp_conf_with_overrides.yaml, spec/lib/simp/cli/config/items/action/set_grub_password_action_spec.rb, spec/lib/simp/cli/config/items/data/grub_password_spec.rb, spec/support/modules/kv_test/metadata.json, spec/support/modules/passgen_test/metadata.json
=> (SIMP-9018) simp-cli remove EL6 support

build/rubygem-simp-cli.spec
* Added simp_grub as a dependency
* Changed all dependencies to weak dependencies so that packages are not removed
if the RPM is uninstalled
SIMP-10568 #close
=> (SIMP-10568) Fix EL8 dependencies
